worker_processes auto;
events {
   worker_connections  1024;
}

http {
   include       mime.types;
   default_type  application/octet-stream;
   sendfile        on;
   keepalive_timeout  15;
   server_tokens     off;

   client_max_body_size     50m;
   client_body_buffer_size  256k;
   client_header_timeout    60s;
   client_body_timeout      60s;

   # 代理超时（关键！解决504）
   proxy_connect_timeout 60s;
   proxy_send_timeout 60s;
   proxy_read_timeout 60s;

   gzip on;
   gzip_min_length 1k;
   gzip_buffers 4 16k;
   gzip_comp_level 4;
   gzip_types
       text/plain
       text/css
       application/javascript
       application/x-javascript
       text/xml
       application/xml
       application/xml+rss
       text/javascript;
   gzip_vary on;

   # 前台博客 80端口
   server {
       listen 80;
       server_name _;

        ## ssl on;
        ## ssl_certificate ssl证书文件位置;
        ## ssl_certificate_key ssl证书文件位置;
        ## ssl_session_timeout 5m;
        ## ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
        ## ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ## ssl_prefer_server_ciphers on;

       location / {
           root /usr/local/aurora-vue/blog;
           index index.html index.htm;
           try_files $uri $uri/ /index.html;
       }

       location ^~ /api/ {
           proxy_pass http://127.0.0.1:9080/;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       }
   }

   # 后台管理 9010端口
   server {
       listen 9010;
       server_name _;

       location / {
           root /usr/local/aurora-vue/admin;
           index index.html index.htm;
           try_files $uri $uri/ /index.html;
       }

       location ^~ /api/ {
           proxy_pass http://127.0.0.1:9080/;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       }
   }
}